# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeSNSTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeSNSTest
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket',
  'RCTImage',
  'RCTAnimation' # needed for debugging
  # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => "../node_modules/react-native/ReactCommon/yoga"
  
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'
  pod 'Firebase/Database', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'
  
  pod 'FBSDKLoginKit'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  
  pod 'GoogleSignIn'
  
  pod 'TwitterKit', '~> 3.3.0'
  pod 'react-native-twitter-signin', :path => '../node_modules/react-native-twitter-signin'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == "React"
          target.remove_from_project
      end
  end
end
